import math
print("Введите 1 сторону:")
a=float(input())
print("1 сторона =", a)
print("Введите 2 сторону:")
b=float(input())
print("2 сторона =", b)
print("Введите угол в градусах:")
c=float(input())
print("Угол =",c)
x=float(math.sqrt((math.pow(a,2))+(math.pow(b,2))-(2*a*b*math.cos(math.radians(c)))))
print("3 сторона =",x)
